Suppress NewApi error to unblock SDK finalization
Suppress the following NewApi lint warning

  [...]/Ts43PhoneNumberController.java:220: Error:
        Call requires API level CUR_DEVELOPMENT/10000 (current min is 36):
	android.telephony.SubscriptionManager#setTs43PhoneNumber [NewApi]

Bug: 480974361
Test: m TARGET_RELEASE=trunk_staging RUN_ERROR_PRONE=true out/soong/.intermediates/packages/modules/Telephony/framework/framework-platformtelephony.impl/android_common/lint/lint-baseline.xml
Flag: NONE platform SDK finalization
Change-Id: I8c77b98551be4a2b8f2966ca238b2c032bac4ae1